language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build -c Release
 - dotnet pack -c Release -o nupkgs
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && dotnet nuget push -s https://www.nuget.org -k $NUGET_API_KEY src/StaticFileTransform/nupkgs/StaticFileTransform.*.nupkg
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && dotnet nuget push -s https://www.nuget.org -k $NUGET_API_KEY src/StaticFileTransform.Abstractions/nupkgs/StaticFileTransform.Abstractions.*.nupkg
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && dotnet nuget push -s https://www.nuget.org -k $NUGET_API_KEY src/StaticFileTransform.NUglify/nupkgs/StaticFileTransform.NUglify.*.nupkg
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && dotnet nuget push -s https://www.nuget.org -k $NUGET_API_KEY src/StaticFileTransform.dotless/nupkgs/StaticFileTransform.dotless.*.nupkg